### ISSUE TITLE
Mapping with read

### ISSUE THREAD

**Issue by neverfox** [cognitect/transit-clj#28]
How can one go about reading from a reader with an arbitrary number of multiple values on the stream without hitting an `EOFException`? For example:

```
(def out (ByteArrayOutputStream. 4096))
(def writer (transit/writer out :json))
(map (partial transit/write writer) some-collection)
(def in (ByteArrayInputStream. (.toByteArray out)))
(def reader (transit/reader in :json))
```

Now I'd like to do as many `transit/read` calls as are necessary to read the whole stream, but no more, preferably through a `map` or `reduce` construct, but it's not clear how to go about that. There doesn't appear to be a way to query the reader about whether there are more items to read.

**Comment by timewald** [comment]
There is no way to query the reader about how many forms are in the stream
because there is no way for it to know. If, for instance, it was a network
stream, a reader could be reading while a writer on a server is still
writing, and may write forever.

If I was writing, then reading a collection that I wanted to then process,
I would typically write the collection in its entirety - so one write call
and one read call.

If I wanted to read the items in the collection individually for some
reason - maybe to parallelize reading and writing or maybe to avoid having
a large collection in memory, I would either write the size of the
collection before the items (assuming I knew it in advance) and then read
that many forms, or I would write all the items and then an end marker of
some sort that the reader could look for.

Tim-

On Sat, Mar 19, 2016 at 3:36 PM, Roman Pearah <notifications@github.com>
wrote:

> How can one go about reading from a reader with an arbitrary number of
> multiple values on the stream without hitting an EOFException? For
> example:
>
> (def out (ByteArrayOutputStream. 4096))
> (def writer (transit/writer out :json))
> (map (partial transit/write writer) some-collection)
> (def in (ByteArrayInputStream. (.toByteArray out)))
> (def reader (transit/reader in :json))
>
> Now I'd like to do as many transit/read calls as are necessary to read
> the whole stream, but no more, preferably through a map or reduce
> construct, but it's not clear how to go about that. There doesn't appear to
> be a way to query the reader about whether there are more items to read.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cognitect/transit-clj/issues/28>
>



-- 
Datomic Team

**Comment by neverfox** [comment]
Thought that might be the case. Thanks, @timewald.

**Comment by neverfox** [comment]
All that said, are there any plans to offer other ways in the API to move items in and out of transit without going through the whole stream ceremony?

**Comment by timewald** [comment]
Streams are essential, not ceremonial, as the underlying json and msgpack
libs work on streams. There are no plans for other APIs layered on top of
them at the moment.

On Sat, Mar 19, 2016 at 7:38 PM, Roman Pearah <notifications@github.com>
wrote:

> All that said, are there any plans to offer other ways in the API to move
> items in and out of transit without going through the whole stream ceremony?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cognitect/transit-clj/issues/28#issuecomment-198807977>
>



-- 
Datomic Team
